<?php
date_default_timezone_set("Asia/Bangkok");
$user="root";
$password="tiger";
$host="mysql";
$db="book";
$con=mysqli_connect($host,$user,$password);
mysqli_select_db($con,$db);
mysqli_set_charset($con,"utf8");
?>
